"""Conexión y creación de tablas PostgreSQL para TecnoAyuda."""
import os
import psycopg


def conectar():
    url = os.environ.get('DATABASE_URL')
    if not url:
        raise RuntimeError('Configura DATABASE_URL en .env o en Render para conectar PostgreSQL.')
    return psycopg.connect(url, connect_timeout=10)


def crear_base_datos():
    conn = conectar()
    try:
        # Evitar que dos procesos creen las tablas simultáneamente.
        conn.execute('SELECT pg_advisory_xact_lock(74162026)')
        instrucciones = """
            CREATE TABLE IF NOT EXISTS productos (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre TEXT NOT NULL,
                descripcion TEXT NOT NULL,
                precio NUMERIC(12, 2) NOT NULL CHECK (precio >= 0)
            );
            CREATE TABLE IF NOT EXISTS administradores (
                id INTEGER PRIMARY KEY CHECK (id = 1),
                usuario TEXT NOT NULL UNIQUE,
                clave_hash TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS solicitudes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre TEXT NOT NULL,
                descripcion TEXT NOT NULL,
                categoria TEXT NOT NULL,
                fecha TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
            );
            CREATE TABLE IF NOT EXISTS clientes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre TEXT NOT NULL,
                correo TEXT NOT NULL,
                telefono TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS cuentas_clientes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id INTEGER NOT NULL UNIQUE,
                correo TEXT NOT NULL UNIQUE,
                clave_hash TEXT NOT NULL,
                fecha TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text),
                FOREIGN KEY (cliente_id) REFERENCES clientes(id)
            );
            CREATE TABLE IF NOT EXISTS proveedores (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre TEXT NOT NULL,
                contacto TEXT NOT NULL,
                servicio TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS facturacion (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id INTEGER NOT NULL,
                producto_id INTEGER NOT NULL,
                cantidad INTEGER NOT NULL CHECK (cantidad > 0),
                precio_unitario NUMERIC(12, 2) NOT NULL CHECK (precio_unitario >= 0),
                total NUMERIC(12, 2) NOT NULL CHECK (total >= 0),
                fecha TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text),
                FOREIGN KEY (cliente_id) REFERENCES clientes(id),
                FOREIGN KEY (producto_id) REFERENCES productos(id)
            );
            CREATE TABLE IF NOT EXISTS pedidos (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_id INTEGER NOT NULL,
                producto_id INTEGER NOT NULL,
                factura_id INTEGER NOT NULL UNIQUE,
                servicio TEXT NOT NULL,
                descripcion TEXT NOT NULL,
                estado_trabajo TEXT NOT NULL DEFAULT 'Recibido',
                fecha TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text),
                FOREIGN KEY (cliente_id) REFERENCES clientes(id),
                FOREIGN KEY (producto_id) REFERENCES productos(id),
                FOREIGN KEY (factura_id) REFERENCES facturacion(id)
            );
ALTER TABLE facturacion ADD COLUMN IF NOT EXISTS metodo_pago TEXT NOT NULL DEFAULT 'No indicado';
ALTER TABLE facturacion ADD COLUMN IF NOT EXISTS referencia TEXT NOT NULL DEFAULT '';
ALTER TABLE facturacion ADD COLUMN IF NOT EXISTS estado TEXT NOT NULL DEFAULT 'Pendiente';
ALTER TABLE facturacion ADD COLUMN IF NOT EXISTS fecha_pago TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS observaciones TEXT NOT NULL DEFAULT '';
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS archivo_guardado TEXT NOT NULL DEFAULT '';
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS archivo_original TEXT NOT NULL DEFAULT '';
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS archivo_contenido BYTEA;
CREATE INDEX IF NOT EXISTS ix_facturacion_cliente ON facturacion(cliente_id);
CREATE INDEX IF NOT EXISTS ix_facturacion_producto ON facturacion(producto_id);
CREATE INDEX IF NOT EXISTS ix_pedidos_cliente ON pedidos(cliente_id);
        """
        for instruccion in instrucciones.split(';'):
            if instruccion.strip():
                conn.execute(instruccion)
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
